import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {describe,it,expect} from 'vitest';
const t=(...p:string[])=>readFileSync(resolve(process.cwd(),...p),'utf8');
describe('Layer 4 contracts',()=>{const w=t('runtime/game/src/web/WebPersistence.lua'),b=t('runtime/game/src/web/BrowserBootstrap.lua'),e=t('runtime/game/src/web/BrowserEvents.lua'),s=t('runtime/game/src/core/SaveData.lua');
it('uses FIFO byte snapshots for saves and coalesces only options',()=>{expect(w).toContain('W.saves[#W.saves+1]=snapshot("save")');expect(w).toContain('W.options=snapshot("options")');expect(s).toContain('webPersistenceSuppressed');});
it('uses each issued id exactly once and validates matching acks',()=>{expect(b).toContain('local function sync(id)');expect(b).toContain('waitForSync(id or Events.requestSync())');expect(b).toContain('local function syncPersistence(id, domain)');expect(w).toContain('fn(id,domain)');expect(w).toContain('got~=id or ok~=id');});
it('persists monotonic ids, rolls pointers back, and recovers main tmp bak active previous',()=>{for(const x of ['save-generation-sequence','POKEVOXEL_GENERATION_EXISTS','restorePointers(old)','{"save-pointer.main","save-pointer.tmp","save-pointer.bak"}','q.active,q.previous','not wanted[x]'])expect(w).toContain(x);});
it('keeps cache generic and ordinary marker domain scoped',()=>{expect(e).toContain('requestSync');expect(e).toContain('requestPersistence(domain)');expect(w).toContain('Events.requestSync()');expect(w).toContain('Events.requestPersistence(s.domain)');});
it('uses a bounded mailbox and single Lua abort retry',()=>{expect(b).toContain('POKEVOXEL_SYNC_TIMEOUT');expect(b).toContain('POKEVOXEL_SYNC_ABORTED');expect(w).toContain('c=="POKEVOXEL_SYNC_ABORTED"');});});

describe('cache clear and web save copy',()=>{const b=t('runtime/game/src/web/BrowserBootstrap.lua'),m=t('runtime/game/main.lua'),start=t('runtime/game/src/ui/StartMenu.lua');it('accepts only the fixed cache-clear mode and excludes saves',()=>{for(const x of ['--pokevoxel-clear-cache','cache-generations','cache-pointer.tmp','cache-pointer.bak','cache-pointer.main','cache-cleared'])expect(b).toContain(x);for(const x of ['save-generations','save-pointer','options.lua'])expect(b).not.toContain(x);});it('forwards load args and avoids browser premature success copy',()=>{expect(m).toContain('function love.load(args) B.load(args) end');expect(start).toContain('Saving to browser\\nstorage...');expect(start).toContain('love.system.getOS() == "Web"');});});
