import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
const root = process.cwd(); const text = (...p: string[]) => readFileSync(resolve(root, ...p), 'utf8');

describe('Layer 7A water source contracts', () => {
  it('activates retained Water and rejects unavailable reflection instead of downgrading', () => {
    const main = text('runtime', 'mods', 'dramatic-shape', 'main.lua');
    const scene = text('runtime', 'mods', 'dramatic-shape', 'lib', 'VoxelScene.lua');
    const voxel = text('runtime', 'mods', 'dramatic-shape', 'lib', 'Voxel3D.lua');
    expect(main).toContain('local Water = V.require("Water")');
    expect(main).toContain('reportDrawFailure(canvas)');
    expect(main).toContain('print(file .. ":" .. line .. ": render exception")');
    expect(main).toContain('detail:upper():gsub("[^A-Z0-9]+", "_"):sub(1, 96)');
    expect(main).toContain('code = "POKEVOXEL_VOXEL_EXCEPTION_" .. detail');
    expect(main).toContain('waterEmittedKey == key');
    expect(main).toContain('not require("src.world.Map").isOutdoor(map.def)');
    expect(main).toContain('waterStableKey, waterEmittedKey, waterStableFrames = nil, nil, 0');
    expect(main).not.toContain('print(tostring(err');
    expect(scene).toContain('local Water = V.require("Water")');
    expect(scene).toContain('POKEVOXEL_WATER_DEPTH_UNAVAILABLE');
    expect(scene).toContain('POKEVOXEL_WATER_SHADER_UNAVAILABLE');
    expect(scene).toContain('local beginOk, began, beginFailure = xpcall(function()');
    expect(scene).toContain('trace:match("Voxel3D%.lua:(%d+)")');
    expect(scene).toContain('POKEVOXEL_VOXEL_SCENE_BEGIN_LINE_');
    expect(scene).toContain('return nil, beginFailure');
    expect(scene).toContain('POKEVOXEL_VOXEL_SCENE_END_FAILED');
    expect(scene).toContain('POKEVOXEL_VOXEL_SCENE_BEGIN_FAILED');
    expect(scene).toContain('POKEVOXEL_VOXEL_SCENE_DRAW_FAILED');
    expect(scene).toContain('POKEVOXEL_VOXEL_PREFETCH_EXCEPTION');
    expect(scene).toContain('POKEVOXEL_VOXEL_SHADOW_PASS_EXCEPTION');
    expect(scene).toContain('POKEVOXEL_VOXEL_SCENE_BEGIN_EXCEPTION');
    expect(scene).toContain('POKEVOXEL_VOXEL_SCENE_DRAW_EXCEPTION');
    expect(scene).toContain('POKEVOXEL_VOXEL_SCENE_END_EXCEPTION');
    expect(main).toContain('tostring(renderFailure):match("^POKEVOXEL_")');
    expect(main).toContain('A clean nil is the asynchronous map-mesh handoff.');
    expect(main).not.toContain('if not canvas and not Voxel.ready then');
    expect(voxel).toContain('return false, "POKEVOXEL_WATER_DEPTH_UNAVAILABLE"');
    expect(voxel).toContain('madeType == "userdata" or madeType == "table"');
    expect(voxel).toContain('local ok, made = xpcall(function()');
    expect(voxel).toContain('love.graphics.getCanvasFormats(true)');
    expect(voxel).toContain('local DEPTH_FORMATS = { "depth16",');
    expect(voxel).toContain('uniform float packDepth;');
    expect(voxel).toContain('gl_FragCoord.z');
    expect(voxel).toContain('local function newDepth(w, h)');
    expect(voxel).toContain('w, h, { format = format, readable = true }');
    expect(voxel).not.toContain('depthAttachment');
    expect(voxel).toContain('local DEPTH_RESTORE_SHADER = [[');
    expect(voxel).toContain('function Voxel3D.beginDepthRestore()');
    expect(voxel).toContain('love.graphics.setColorMask(false, false, false, false)');
    expect(voxel).toContain('function Voxel3D.drawDepth(mesh, model)');
    expect(voxel).toContain('function Voxel3D.endDepthRestore()');
    expect(voxel).toContain('or { held.mirror, depth = true }');
    expect(voxel).toContain('return held.mirror, held.depth or held.mirror');
    expect(voxel).toContain('function Voxel3D.depthPacked()');
    expect(main).not.toContain('VOXEL_RENDER_SCALE');
    expect(main).toContain('local width, height = sceneSize(ctx)');
    expect(voxel).not.toContain('WATER_SCALE');
    expect(voxel).not.toContain('waterLayer');
    expect(voxel).toContain('love.graphics.setCanvas, canvas');
    expect(voxel).toContain('love.graphics.setDepthMode("lequal", true)');
    expect(voxel).toContain('function Voxel3D.beginWater(paint, restoreDepth)');
    expect(voxel).not.toContain('mirrorKey');
    expect(scene).toContain('local curved = (Voxel3D.curveK or 0) > 0');
    expect(scene).toContain('screen = { w, h }, cell = Voxel3D.cell');
    expect(scene).toContain('put(p.px); put(p.py); put(p.gh); put(p.lift or 0)');
    expect(scene).toContain('put(p.facing); put(p.phase); put(p.flip and 1 or 0)');
    const shadow = text('runtime', 'mods', 'dramatic-shape', 'lib', 'ShadowMap.lua');
    expect(scene).toContain('local fitSig = ShadowMap.prepare(cx, cy, vw, vh)');
    expect(shadow).toContain('local qx = math.floor(cx / step + 0.5) * step');
    expect(shadow).toContain('local qy = math.floor(cy / step + 0.5) * step');
    expect(scene).toContain('ChunkMesher.request(state.map, false, masks, true)');
    expect(scene).toContain('ChunkMesher.request(nb.map, true)');
    expect(scene).not.toContain('if needsRing then');
    expect(scene).not.toContain('if visibleNeighbor then');
    expect(scene).toContain('local plain = not curved');
    expect(scene).not.toContain('reflectionKey');
    expect(scene).toContain('local function neighborInView(nb)');
    expect(scene).toContain('nb.ox + def.width * 32 > left');
    expect(scene).toContain('local function drawTerrainDepth()');
    expect(scene).toContain('POKEVOXEL_VOXEL_DEPTH_RESTORE_FAILED');
    expect(scene).toContain('drawTerrainDepth)');
    expect(text('runtime', 'game', 'src', 'render', 'Renderer.lua')).toContain('ww / overrideW, wh / overrideH');
    const water = text('runtime', 'mods', 'dramatic-shape', 'lib', 'Water.lua');
    expect(water).toContain('Water.RAY_STEPS = 24');
    expect(water).toContain('Water.RAY_REFINE = 5');
    expect(water).toContain('#ifdef FULL_RAYS');
    expect(water).toContain('if fullRays then head = head .. "#define FULL_RAYS 1\\n" end');
    expect(water).toContain('local fullRays = level >= 2');
    expect(water).toContain('Water.shader(true, fullRays)');
    expect(water).toContain('Water.shader(false, fullRays)');
    expect(water).not.toContain('uniform float rays;');
    expect(water).not.toContain('send("rays"');
    expect(water).toContain('waveBase = waveRaw(col);');
    expect(water).toContain('float y = base.y + waveAtRaw(raw);');
    expect(water).toContain('waveNormal(col, waveBase,');
    expect(water).not.toContain('float h = waveRaw(q);');
    expect(water).toContain('uniform float depthPacked;');
    expect(water).toContain('float sceneDepth(vec2 uv)');
    expect(water).toContain('send("depthPacked", ctx.depthPacked and 1 or 0)');
    expect(voxel).toContain('not supported or supported[format] == true');
    expect(voxel).toContain('return love.graphics.newCanvas(');
    expect(voxel).toContain('return made:getDimensions()');
    expect(voxel).toContain('dimensionsOk and madeW == w and madeH == h');
    expect(voxel).toContain('pcall(function() c:setDepthSampleMode() end)');
    expect(voxel).toContain('pcall(function() mesh:setTexture(texture) end)');
    expect(voxel).toContain('pcall(function() love.graphics.draw(mesh) end)');
    expect(voxel).toContain('POKEVOXEL_VOXEL_SHADER_UNAVAILABLE');
    expect(voxel).toContain('POKEVOXEL_VOXEL_CANVAS_UNAVAILABLE');
    expect(voxel).toContain('POKEVOXEL_VOXEL_DEPTH_UNAVAILABLE');
    expect(voxel).not.toContain('fall back to the internal buffer');
    expect(scene).toContain('return false, lastWaterEvidence.failure');
  });
  it('keeps all map/Surf/failure controls in the disposable water driver', () => {
    const driver = text('tests', 'runtime', 'water-scenario-driver.lua');
    for (const value of ['ROUTE_19', 'ROUTE_20', 'REDS_HOUSE_1F', 'G.save.surfing', 'W.begin = function() return false end']) expect(driver).toContain(value);
    expect(text('runtime', 'game', 'src', 'web', 'BrowserBootstrap.lua')).not.toContain('POKEVOXEL_TEST_WATER_SCENARIOS');
  });
  it('registers the private water lane and the G008 goal stages', () => {
    const pkg = JSON.parse(text('package.json')) as { scripts: Record<string, string> };
    expect(pkg.scripts['test:browser:water:focused']).toContain('--water-scenarios');
    const browser = text('tests', 'browser', 'water.spec.ts');
    expect(browser).toContain("document.querySelector<HTMLElement>('[data-testid=\"water-probe\"]')?.innerText");
    expect(browser).not.toContain("const node = page.getByTestId('water-probe');");
    expect(browser).toContain('const performanceTest = test.extend({});');
    expect(browser).toContain("performanceTest.use({ trace: 'off' });");
    expect(browser).toContain("performanceTest('renders SKY/FULL shoreline and Surf routes without fallback within the browser budget'");
    expect(browser).toContain("test('clears water evidence indoors and rejects an allocation/shader failure instead of downgrading'");
    const checks = text('scripts', 'lib', 'checks.mjs');
    expect(checks).toContain("goal === 'G008'");
    expect(checks).toContain("'water-browser'");
  });
  it('contains optional shadow-caster GPU failures without accepting a flat water fallback', () => {
    const shadow = text('runtime', 'mods', 'dramatic-shape', 'lib', 'ShadowMap.lua');
    expect(shadow).not.toContain('pcall(mesh.setTexture, mesh, texture)');
    expect(shadow).toContain('pcall(function() mesh:setTexture(texture) end)');
    expect(shadow).toContain('return pcall(function() love.graphics.draw(mesh) end)');
    expect(text('runtime', 'mods', 'dramatic-shape', 'lib', 'VoxelScene.lua')).toContain('return false, lastWaterEvidence.failure');
  });
});
