import { describe, expect, it, vi } from 'vitest';
import { CANONICAL_ROM_SIZE, ROM_PROFILES, clearRomBuffer, validateGen1Rom } from '../../src/import/romValidation';

type TestFile = { size: number; arrayBuffer(): Promise<ArrayBuffer> };
const generatedFile = (size: number, fill = 0): TestFile => ({ size, arrayBuffer: async () => new Uint8Array(size).fill(fill).buffer });
const digestBytes = (hex: string) => Uint8Array.from(hex.match(/../g)!.map((value) => Number.parseInt(value, 16))).buffer;

describe('validateGen1Rom', () => {
  it('owns the exact retained Red, Blue, and Yellow profile table', () => {
    expect(ROM_PROFILES).toEqual([
      { id: 'red', label: 'Red', sha1: 'ea9bcae617fdf159b045185467ae58b2e4a48b9a' },
      { id: 'blue', label: 'Blue', sha1: 'd7037c83e1ae5b39bde3c30787637ba1d4c48ce2' },
      { id: 'yellow', label: 'Yellow', sha1: 'cc7d03262ebfaf2f06772c1a480c7d9d5f4a38e1' },
    ]);
    expect(CANONICAL_ROM_SIZE).toBe(1_048_576);
  });

  it('detects every retained version by canonical SHA-1', async () => {
    for (const profile of ROM_PROFILES) {
      const bytes = new Uint8Array(CANONICAL_ROM_SIZE).fill(profile.id.length);
      const result = await validateGen1Rom({ size: bytes.byteLength, arrayBuffer: async () => bytes.buffer } as File, { digest: async () => digestBytes(profile.sha1) });
      expect(result.ok).toBe(true);
      if (result.ok) {
        expect(result.version).toBe(profile.id);
        expect(new Uint8Array(result.buffer)[0]).toBe(profile.id.length);
      }
    }
  });

  it('rejects a wrong-size file before calculating its digest', async () => {
    const digest = vi.fn();
    expect(await validateGen1Rom(generatedFile(CANONICAL_ROM_SIZE - 1) as File, { digest })).toEqual({ ok: false, code: 'wrong-size' });
    expect(digest).not.toHaveBeenCalled();
  });

  it('returns a typed unreadable error without calling the digest', async () => {
    const digest = vi.fn();
    const unreadable: TestFile = { size: CANONICAL_ROM_SIZE, arrayBuffer: async () => { throw new Error('read failure'); } };
    expect(await validateGen1Rom(unreadable as File, { digest })).toEqual({ ok: false, code: 'unreadable' });
    expect(digest).not.toHaveBeenCalled();
  });

  it('rejects an unknown digest and clears generated bytes', async () => {
    const bytes = new Uint8Array(CANONICAL_ROM_SIZE).fill(7);
    const result = await validateGen1Rom({ size: bytes.byteLength, arrayBuffer: async () => bytes.buffer } as File, { digest: async () => digestBytes('0'.repeat(40)) });
    expect(result).toEqual({ ok: false, code: 'wrong-digest' });
    expect(bytes.every((byte) => byte === 0)).toBe(true);
  });

  it('zeroes bytes when callers clear accepted buffers after retry or fatal cleanup', () => {
    for (const fill of [1, 2, 3]) { const buffer = new Uint8Array(32).fill(fill).buffer; clearRomBuffer(buffer); expect([...new Uint8Array(buffer)]).toEqual(new Array(32).fill(0)); }
  });
});

it.skipIf(!process.env.POKEVOXEL_TEST_ROM_PATH)('validates and stages the configured private canonical ROM without exposing its path', async () => {
  const { readFileSync } = await import('node:fs');
  const { LoveRuntimeAdapter, STAGED_ROM_PATH } = await import('../../src/runtime/LoveRuntimeAdapter');
  const privateBytes = readFileSync(process.env.POKEVOXEL_TEST_ROM_PATH!);
  const source = privateBytes.buffer.slice(privateBytes.byteOffset, privateBytes.byteOffset + privateBytes.byteLength);
  const result = await validateGen1Rom({ size: privateBytes.byteLength, arrayBuffer: async () => source } as File);
  expect(result.ok).toBe(true);
  if (!result.ok) return;
  let stagedPath: string | undefined;
  let staged: Uint8Array | undefined;
  await new LoveRuntimeAdapter({ stageFile: async (path, data) => { stagedPath = path; staged = new Uint8Array(data).slice(); } }).stageRom(result.buffer);
  expect(result.version).toBe('yellow');
  expect(STAGED_ROM_PATH).toBe('/tmp/pokevoxel-rom.gb');
  expect(stagedPath).toBe(STAGED_ROM_PATH);
  expect(staged?.byteLength).toBe(CANONICAL_ROM_SIZE);
  expect(new Uint8Array(result.buffer).every((byte) => byte === 0)).toBe(true);
});
